Libertad/katas
fjcoding/AT18 pull request #54
Opened 2022-08-08 13:21 UTC by TolabaLib

2022-08-09 02:47 UTC, J0c4 requested changes
Hi @TolabaLib , please update the PR to point the correct target branch, it should be dev/katas instead of main

2022-08-09 03:05 UTC, TolabaLib commented
Sorry, I didn't realize it, but I've changed it. Thanks

El lun, 8 ago 2022 a las 22:47, Jose Carlos ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Hi @TolabaLib <https://github.com/TolabaLib> , please update the PR to
> point the correct target branch, it should be dev/katas instead of main
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fjcoding/AT18/pull/54#pullrequestreview-1066021321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQL7C5MSTFUAH4BQDQYDMA3VYHBFDANCNFSM555DUMXA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-09 03:17 UTC, J0c4 requested changes

2022-08-09 03:17 UTC, J0c4 commented on src/main/java/jalau/at18/katas/highestlowest/libertad/Main.java
> +        System.out.println("Introdusca los numeros:");
Please use english for all the code

2022-08-10 04:16 UTC, J0c4 requested changes
Hi @TolabaLib , your implementation looks good, it is almost ready to be merged, but I noticed that Main files for likes, multiples and phonenumber katas are missing file extension `.java`, this could cause some potential issues with project build, please fix it by renaming the files and pushing that change

Also, let me know in case you are planning to add unit tests in a separate PR

2022-08-10 04:28 UTC, TolabaLib commented
> Hola@TolabaLib, su implementación se ve bien, está casi lista para fusionarse, pero noté que a los archivos principales para me gusta, múltiplos y katas de números de teléfono les falta la extensión de archivo `.java`, esto podría causar algunos problemas potenciales con la compilación del proyecto, corríjalo cambiando el nombre de los archivos y empujando ese cambio
> 
> Además, avíseme en caso de que esté planeando agregar pruebas unitarias en un PR separado

2022-08-12 05:07 UTC, J0c4 submitted a review, later dismissed

2022-08-12 21:57 UTC, TolabaLib commented
Jose I have already solved the problems, could you check my pull request

2022-08-12 22:00 UTC, J0c4 approved these changes

2022-08-12 22:00 UTC, merged