Danieladev/katas
fjcoding/AT18 pull request #55
Opened 2022-08-08 13:26 UTC by DaniMB95

"Because of some problems in my daniela branch i create a new branch with my 4 katas but actualice with the origin/dev/katas

2022-08-09 02:52 UTC, J0c4 requested changes
Hi @DaniMB95 , your code looks good, however, there are some changes in this PR that should be reverted, please check my comments

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -apply plugin: 'checkstyle'
this plugin must not be removed

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -dependencies {
please restore this dependency

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -test {
This configuration should be restored

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -checkstyle {
this configuration should be restored

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -checkstyleMain {
Please restore this setting

2022-08-09 02:52 UTC, J0c4 commented on build.gradle
> -test.finalizedBy("checkstyleMain")
please restore this line

2022-08-09 02:52 UTC, J0c4 commented on src/main/java/jalau/at18/katas/highestlowest/daniela/highestlowest.java
> +        String numeros = "1 2 3 4 8 6";
please use english for all your code

2022-08-09 02:52 UTC, J0c4 commented on src/test/java/jalau/at18/katas/helloworld/joseg/MainTest.java
> -import static org.junit.Assert.*;
These files should not change, please revert this

2022-08-09 02:52 UTC, J0c4 commented on src/test/java/jalau/at18/katas/helloworld/joseg/Test.java
> +package jalau.at18.katas.helloworld.joseg;
Maybe this was created by the editor, but it's not needed, please remove it

2022-08-10 01:01 UTC, DaniMB95 commented
I complete the test for 3 of 4 katas.

2022-08-10 04:25 UTC, J0c4 requested changes
Good work Daniela, please see my new comments, there are few things that need to be adjusted and this should be ok to go

2022-08-10 04:25 UTC, J0c4 commented on src/test/java/jalau/at18/katas/likes/daniela/LikesTest.java
> +        String output1 = "Daniela ,Alejandra and 2 others likes this";
There is an unexpected space between "Daniela" and ",", and there is a missing space between "," and "Alejandra". This is defined in the kata requirement:
```
["Alex", "Jacob", "Mark", "Max"]  -->  "Alex, Jacob and 2 others like this"
```
Please update it so it matches kata requirement. The other verifications look good

2022-08-10 04:25 UTC, J0c4 commented on src/test/java/jalau/at18/katas/likes/daniela/LikesTest.java
> +        //String[] finalnamecase5 = {};
`finalnamecase4` and `finalnamecase5` should be verified as well, why were those commented?

2022-08-10 04:25 UTC, J0c4 commented on src/test/java/jalau/at18/katas/multiple/daniela/MainTest.java
> +    public void functionShouldGiveHighest() {
Not sure if test name is ok because this test is actually verifying method that sums multiples instead for give "highest"

2022-08-10 04:25 UTC, J0c4 commented on src/test/java/jalau/at18/katas/phonenumber/daniela/PhonenumberTest.java
> +        var outnumber = "(123)456-7890";
Missing space between ")" and "4". Please update it so it matches kata requirement
```
createPhoneNumber([1, 2, 3, 4, 5, 6, 7, 8, 9, 0]) // => returns "(123) 456-7890"
```

2022-08-10 04:26 UTC, J0c4 commented
Also, please fix conflicts reported, otherwise, we will not be able to merge this PR

2022-08-11 14:39 UTC, DaniMB95 commented
Already fixed the changes of my test cases and solve the conflict already

2022-08-12 05:09 UTC, J0c4 submitted a review, later dismissed
Nice job!

2022-08-12 13:38 UTC, DaniMB95 commented
@J0c4, I have already solve a conflict before merge but I need again you review 
Thanks in advance

2022-08-12 21:36 UTC, J0c4 submitted a review, later dismissed

2022-08-12 22:14 UTC, DaniMB95 commented
@J0c4 Dear jose,
I already fixed the conflicts, I need again your aprove :)

2022-08-12 22:17 UTC, J0c4 approved these changes

2022-08-12 22:17 UTC, merged