Team4/kata2048
fjcoding/AT18 pull request #74
Opened 2022-08-13 01:30 UTC by HugoS922

Hello Jose, Team4 status: Finishing game 2048, adding minor fixes with operability and information displayed, adding final format and unit tests

2022-08-14 05:04 UTC, J0c4 requested changes
Great work guys, tests were good and code looks well separated.

Please check my comments as there are some adjustments you need to make, let me know in case you have any comments

2022-08-14 05:04 UTC, J0c4 commented on src/test/java/jalau/at18/katas/game2028/team4/MainTest.java
> +        int[][] expectedMatrix = {{NUMBER_TWO, NUMBER_TWO, NUMBER_TWO, NUMBER_TWO},
if moved up, there are some "2"s that should be merged and then expected should end up with some "4"s from merged tiles, is the merging part of this operation or is it something that is in a separated method?

2022-08-14 05:04 UTC, J0c4 commented on src/test/java/jalau/at18/katas/game2028/team4/MainTest.java
> +			{NUMBER_TWO, NUMBER_TWO, NUMBER_TWO, NUMBER_TWO}, {NUMBER_TWO, NUMBER_TWO, NUMBER_TWO, NUMBER_TWO}};
This test will need to be updated, the matrix still have possible moves so it should not be considered as a loser table

2022-08-14 05:04 UTC, J0c4 commented on src/test/java/jalau/at18/katas/game2028/team4/MainTest.java
> +        Main main = new Main();
same about static vs instance

2022-08-14 07:27 UTC, HugoS922 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +
Deleting empty spaces like this

2022-08-14 07:29 UTC, HugoS922 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +        } while (!isWinner(matrix) && exit != "q" && !isLoser(matrix));
changing order of conditions, now it begins checking if the player wants to finish the game first

2022-08-14 07:31 UTC, HugoS922 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +        matrixToShow[randomPositionX][randomPositionY] = 2;
adding a number generator so that the numbers added to the board could be a two or a four depending (20% chances of geting a new 4)

2022-08-14 07:32 UTC, HugoS922 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +    /* public static String getNextDirection() {
removing unnecesary comments

2022-08-14 07:34 UTC, HugoS922 commented on src/test/java/jalau/at18/katas/game2028/team4/MainTest.java
> +    public static final int NUMBER_TWO = 2;
changing the name of this variable so it is easier to follow when codding

2022-08-14 20:12 UTC, HugoS922 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +    public static boolean isLoser(int[][] matrixToCheck) {
Game ending, this problem now is solved, this game will search for new possible moves, if not found then will end the game

2022-08-15 00:14 UTC, MauricioAliendre182 commented on src/main/java/jalau/at18/katas/game2048/team4/Main.java
> +    public static int[][] moveNumbersDown(int[][] matrixToMove) {
Movement issue solved, now the program has the correct logic

2022-08-15 02:08 UTC, J0c4 approved these changes

2022-08-15 02:19 UTC, HugoS922 commented
Thank you @J0c4 for reviewing and approving this pull request and thanks to @MauricioAliendre182 @Renucopata for participating, now we can merge this branch.

2022-08-15 02:19 UTC, merged